name: My First Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  MyFirstJob:
    runs-on: ubuntu-latest

    steps:
      - name: Hello
        run: echo "Hello World!"

      - name: Checkout
        uses: actions/checkout@v5.0.0

      - name: List files in repo
        run: |
          echo "The repository ${{ github.repository }} contains the following files:"
          tree
